import { EtapaEducativa, ComunidadAutonoma, CompetenciaEspecifica, CriterioEvaluacion, SaberBasico } from '../types';
import { COMPETENCIAS_ESPECIFICAS_EF, CRITERIOS_EVALUACION_EF, SABERES_BASICOS_EF } from '../data/curriculumData';
import { COMPETENCIAS_ESPECIFICAS_INFANTIL, CRITERIOS_EVALUACION_INFANTIL, SABERES_BASICOS_INFANTIL } from '../data/curriculumInfantil';
import { COMPETENCIAS_ESPECIFICAS_ESO, CRITERIOS_EVALUACION_ESO, SABERES_BASICOS_ESO } from '../data/curriculumESO';
import { COMPETENCIAS_ESPECIFICAS_BACHILLERATO, CRITERIOS_EVALUACION_BACHILLERATO, SABERES_BASICOS_BACHILLERATO } from '../data/curriculumBachillerato';
import {
  COMPETENCIAS_ESPECIFICAS_ANDALUCIA_PRIMARIA, COMPETENCIAS_ESPECIFICAS_ANDALUCIA_ESO,
  CRITERIOS_EVALUACION_ANDALUCIA_PRIMARIA, CRITERIOS_EVALUACION_ANDALUCIA_ESO,
  SABERES_BASICOS_ANDALUCIA_PRIMARIA, SABERES_BASICOS_ANDALUCIA_ESO
} from '../data/curriculumAndalucia';
import { 
  COMPETENCIAS_ESPECIFICAS_CYL_PRIMARIA, 
  COMPETENCIAS_ESPECIFICAS_CYL_ESO,
  CRITERIOS_EVALUACION_CYL_PRIMARIA,
  CRITERIOS_EVALUACION_CYL_ESO,
  SABERES_BASICOS_CYL_PRIMARIA,
  SABERES_BASICOS_CYL_ESO 
} from '../data/curriculumCyL';

import {
  COMPETENCIAS_ESPECIFICAS_CLM_PRIMARIA, COMPETENCIAS_ESPECIFICAS_CLM_ESO,
  CRITERIOS_EVALUACION_CLM_PRIMARIA, CRITERIOS_EVALUACION_CLM_ESO,
  SABERES_BASICOS_CLM_PRIMARIA, SABERES_BASICOS_CLM_ESO
} from '../data/curriculumCLM';

import {
  COMPETENCIAS_ESPECIFICAS_EXTREMADURA_PRIMARIA, COMPETENCIAS_ESPECIFICAS_EXTREMADURA_ESO,
  CRITERIOS_EVALUACION_EXTREMADURA_PRIMARIA, CRITERIOS_EVALUACION_EXTREMADURA_ESO,
  SABERES_BASICOS_EXTREMADURA_PRIMARIA, SABERES_BASICOS_EXTREMADURA_ESO
} from '../data/curriculumExtremadura';

import {
  COMPETENCIAS_ESPECIFICAS_MURCIA_PRIMARIA, COMPETENCIAS_ESPECIFICAS_MURCIA_ESO,
  CRITERIOS_EVALUACION_MURCIA_PRIMARIA, CRITERIOS_EVALUACION_MURCIA_ESO,
  SABERES_BASICOS_MURCIA_PRIMARIA, SABERES_BASICOS_MURCIA_ESO
} from '../data/curriculumMurcia';

import {
  COMPETENCIAS_ESPECIFICAS_ARAGON_PRIMARIA, COMPETENCIAS_ESPECIFICAS_ARAGON_ESO,
  CRITERIOS_EVALUACION_ARAGON_PRIMARIA, CRITERIOS_EVALUACION_ARAGON_ESO,
  SABERES_BASICOS_ARAGON_PRIMARIA, SABERES_BASICOS_ARAGON_ESO
} from '../data/curriculumAragon';

import {
  COMPETENCIAS_ESPECIFICAS_ASTURIAS_PRIMARIA, COMPETENCIAS_ESPECIFICAS_ASTURIAS_ESO,
  CRITERIOS_EVALUACION_ASTURIAS_PRIMARIA, CRITERIOS_EVALUACION_ASTURIAS_ESO,
  SABERES_BASICOS_ASTURIAS_PRIMARIA, SABERES_BASICOS_ASTURIAS_ESO
} from '../data/curriculumAsturias';

import {
  COMPETENCIAS_ESPECIFICAS_CANTABRIA_PRIMARIA, COMPETENCIAS_ESPECIFICAS_CANTABRIA_ESO,
  CRITERIOS_EVALUACION_CANTABRIA_PRIMARIA, CRITERIOS_EVALUACION_CANTABRIA_ESO,
  SABERES_BASICOS_CANTABRIA_PRIMARIA, SABERES_BASICOS_CANTABRIA_ESO
} from '../data/curriculumCantabria';

import {
  COMPETENCIAS_ESPECIFICAS_GALICIA_PRIMARIA, COMPETENCIAS_ESPECIFICAS_GALICIA_ESO,
  CRITERIOS_EVALUACION_GALICIA_PRIMARIA, CRITERIOS_EVALUACION_GALICIA_ESO,
  SABERES_BASICOS_GALICIA_PRIMARIA, SABERES_BASICOS_GALICIA_ESO
} from '../data/curriculumGalicia';

import {
  COMPETENCIAS_ESPECIFICAS_CATALUNYA_PRIMARIA, COMPETENCIAS_ESPECIFICAS_CATALUNYA_ESO,
  CRITERIOS_EVALUACION_CATALUNYA_PRIMARIA, CRITERIOS_EVALUACION_CATALUNYA_ESO,
  SABERES_BASICOS_CATALUNYA_PRIMARIA, SABERES_BASICOS_CATALUNYA_ESO
} from '../data/curriculumCatalunya';

import {
  COMPETENCIAS_ESPECIFICAS_LA_RIOJA_PRIMARIA, COMPETENCIAS_ESPECIFICAS_LA_RIOJA_ESO,
  CRITERIOS_EVALUACION_LA_RIOJA_PRIMARIA, CRITERIOS_EVALUACION_LA_RIOJA_ESO,
  SABERES_BASICOS_LA_RIOJA_PRIMARIA, SABERES_BASICOS_LA_RIOJA_ESO
} from '../data/curriculumLa_Rioja';

import {
  COMPETENCIAS_ESPECIFICAS_MADRID_PRIMARIA, COMPETENCIAS_ESPECIFICAS_MADRID_ESO,
  CRITERIOS_EVALUACION_MADRID_PRIMARIA, CRITERIOS_EVALUACION_MADRID_ESO,
  SABERES_BASICOS_MADRID_PRIMARIA, SABERES_BASICOS_MADRID_ESO
} from '../data/curriculumMadrid';

import {
  COMPETENCIAS_ESPECIFICAS_VALENCIA_PRIMARIA, COMPETENCIAS_ESPECIFICAS_VALENCIA_ESO,
  CRITERIOS_EVALUACION_VALENCIA_PRIMARIA, CRITERIOS_EVALUACION_VALENCIA_ESO,
  SABERES_BASICOS_VALENCIA_PRIMARIA, SABERES_BASICOS_VALENCIA_ESO
} from '../data/curriculumValencia';


import {
  COMPETENCIAS_ESPECIFICAS_NAVARRA_PRIMARIA, COMPETENCIAS_ESPECIFICAS_NAVARRA_ESO,
  CRITERIOS_EVALUACION_NAVARRA_PRIMARIA, CRITERIOS_EVALUACION_NAVARRA_ESO,
  SABERES_BASICOS_NAVARRA_PRIMARIA, SABERES_BASICOS_NAVARRA_ESO
} from '../data/curriculumNavarra';

import {
  COMPETENCIAS_ESPECIFICAS_PAIS_VASCO_PRIMARIA, COMPETENCIAS_ESPECIFICAS_PAIS_VASCO_ESO,
  CRITERIOS_EVALUACION_PAIS_VASCO_PRIMARIA, CRITERIOS_EVALUACION_PAIS_VASCO_ESO,
  SABERES_BASICOS_PAIS_VASCO_PRIMARIA, SABERES_BASICOS_PAIS_VASCO_ESO
} from '../data/curriculumPais_Vasco';
export function getCompetenciasByEtapa(etapa: EtapaEducativa, comunidad: ComunidadAutonoma = 'Andalucía'): CompetenciaEspecifica[] {
  if (comunidad === 'Castilla y León') {
    switch (etapa) {
      case 'Primaria': return COMPETENCIAS_ESPECIFICAS_CYL_PRIMARIA;
      case 'ESO': return COMPETENCIAS_ESPECIFICAS_CYL_ESO;
      default: return COMPETENCIAS_ESPECIFICAS_CYL_PRIMARIA; 
    }
  }
  if (comunidad === 'Castilla-La Mancha') {
    switch (etapa) {
      case 'Primaria': return COMPETENCIAS_ESPECIFICAS_CLM_PRIMARIA;
      case 'ESO': return COMPETENCIAS_ESPECIFICAS_CLM_ESO;
      default: return COMPETENCIAS_ESPECIFICAS_CLM_PRIMARIA;
    }
  }
  if (comunidad === 'Extremadura') {
    switch (etapa) {
      case 'Primaria': return COMPETENCIAS_ESPECIFICAS_EXTREMADURA_PRIMARIA;
      case 'ESO': return COMPETENCIAS_ESPECIFICAS_EXTREMADURA_ESO;
      default: return COMPETENCIAS_ESPECIFICAS_EXTREMADURA_PRIMARIA;
    }
  }
  if (comunidad === 'Región de Murcia') {
    switch (etapa) {
      case 'Primaria': return COMPETENCIAS_ESPECIFICAS_MURCIA_PRIMARIA;
      case 'ESO': return COMPETENCIAS_ESPECIFICAS_MURCIA_ESO;
      default: return COMPETENCIAS_ESPECIFICAS_MURCIA_PRIMARIA;
    }
  }
  if (comunidad === 'Aragón') {
    switch (etapa) {
      case 'Primaria': return COMPETENCIAS_ESPECIFICAS_ARAGON_PRIMARIA;
      case 'ESO': return COMPETENCIAS_ESPECIFICAS_ARAGON_ESO;
      default: return COMPETENCIAS_ESPECIFICAS_ARAGON_PRIMARIA;
    }
  }
  if (comunidad === 'Asturias') {
    switch (etapa) {
      case 'Primaria': return COMPETENCIAS_ESPECIFICAS_ASTURIAS_PRIMARIA;
      case 'ESO': return COMPETENCIAS_ESPECIFICAS_ASTURIAS_ESO;
      default: return COMPETENCIAS_ESPECIFICAS_ASTURIAS_PRIMARIA;
    }
  }
  if (comunidad === 'Cantabria') {
    switch (etapa) {
      case 'Primaria': return COMPETENCIAS_ESPECIFICAS_CANTABRIA_PRIMARIA;
      case 'ESO': return COMPETENCIAS_ESPECIFICAS_CANTABRIA_ESO;
      default: return COMPETENCIAS_ESPECIFICAS_CANTABRIA_PRIMARIA;
    }
  }
  if (comunidad === 'Galicia') {
    switch (etapa) {
      case 'Primaria': return COMPETENCIAS_ESPECIFICAS_GALICIA_PRIMARIA;
      case 'ESO': return COMPETENCIAS_ESPECIFICAS_GALICIA_ESO;
      default: return COMPETENCIAS_ESPECIFICAS_GALICIA_PRIMARIA;
    }
  }
  if (comunidad === 'Catalunya' || comunidad === 'Catalunya') {
    switch (etapa) {
      case 'Primaria': return COMPETENCIAS_ESPECIFICAS_CATALUNYA_PRIMARIA;
      case 'ESO': return COMPETENCIAS_ESPECIFICAS_CATALUNYA_ESO;
      default: return COMPETENCIAS_ESPECIFICAS_CATALUNYA_PRIMARIA;
    }
  }
  if (comunidad === 'Comunidad Valenciana') {
    switch (etapa) {
      case 'Primaria': return COMPETENCIAS_ESPECIFICAS_VALENCIA_PRIMARIA;
      case 'ESO': return COMPETENCIAS_ESPECIFICAS_VALENCIA_ESO;
      default: return COMPETENCIAS_ESPECIFICAS_VALENCIA_PRIMARIA;
    }
  }
  if (comunidad === 'La Rioja') {
    switch (etapa) {
      case 'Primaria': return COMPETENCIAS_ESPECIFICAS_LA_RIOJA_PRIMARIA;
      case 'ESO': return COMPETENCIAS_ESPECIFICAS_LA_RIOJA_ESO;
      default: return COMPETENCIAS_ESPECIFICAS_LA_RIOJA_PRIMARIA;
    }
  }
  if (comunidad === 'Comunidad de Madrid') {
    switch (etapa) {
      case 'Primaria': return COMPETENCIAS_ESPECIFICAS_MADRID_PRIMARIA;
      case 'ESO': return COMPETENCIAS_ESPECIFICAS_MADRID_ESO;
      default: return COMPETENCIAS_ESPECIFICAS_MADRID_PRIMARIA;
    }
  }
  if (comunidad === 'Navarra') {
    switch (etapa) {
      case 'Primaria': return COMPETENCIAS_ESPECIFICAS_NAVARRA_PRIMARIA;
      case 'ESO': return COMPETENCIAS_ESPECIFICAS_NAVARRA_ESO;
      default: return COMPETENCIAS_ESPECIFICAS_NAVARRA_PRIMARIA;
    }
  }
  if (comunidad === 'País Vasco') {
    switch (etapa) {
      case 'Primaria': return COMPETENCIAS_ESPECIFICAS_PAIS_VASCO_PRIMARIA;
      case 'ESO': return COMPETENCIAS_ESPECIFICAS_PAIS_VASCO_ESO;
      default: return COMPETENCIAS_ESPECIFICAS_PAIS_VASCO_PRIMARIA;
    }
  }

  if (comunidad === 'Andalucía') {
    switch (etapa) {
      case 'Infantil': return COMPETENCIAS_ESPECIFICAS_INFANTIL;
      case 'Primaria': return COMPETENCIAS_ESPECIFICAS_ANDALUCIA_PRIMARIA;
      case 'ESO': return COMPETENCIAS_ESPECIFICAS_ANDALUCIA_ESO;
      case 'Bachillerato': return COMPETENCIAS_ESPECIFICAS_BACHILLERATO;
      default: return COMPETENCIAS_ESPECIFICAS_ANDALUCIA_PRIMARIA;
    }
  }

  // Fallback para cualquier otra comunidad sin datos específicos
  switch (etapa) {
    case 'Infantil': return COMPETENCIAS_ESPECIFICAS_INFANTIL;
    case 'Primaria': return COMPETENCIAS_ESPECIFICAS_EF;
    case 'ESO': return COMPETENCIAS_ESPECIFICAS_ESO;
    case 'Bachillerato': return COMPETENCIAS_ESPECIFICAS_BACHILLERATO;
    default: return COMPETENCIAS_ESPECIFICAS_EF;
  }
}

export function getCriteriosByEtapa(etapa: EtapaEducativa, comunidad: ComunidadAutonoma = 'Andalucía'): CriterioEvaluacion[] {
  if (comunidad === 'Castilla y León') {
    switch (etapa) {
      case 'Primaria': return CRITERIOS_EVALUACION_CYL_PRIMARIA;
      case 'ESO': return CRITERIOS_EVALUACION_CYL_ESO;
      default: return CRITERIOS_EVALUACION_CYL_PRIMARIA;
    }
  }
  if (comunidad === 'Castilla-La Mancha') {
    switch (etapa) {
      case 'Primaria': return CRITERIOS_EVALUACION_CLM_PRIMARIA;
      case 'ESO': return CRITERIOS_EVALUACION_CLM_ESO;
      default: return CRITERIOS_EVALUACION_CLM_PRIMARIA;
    }
  }
  if (comunidad === 'Extremadura') {
    switch (etapa) {
      case 'Primaria': return CRITERIOS_EVALUACION_EXTREMADURA_PRIMARIA;
      case 'ESO': return CRITERIOS_EVALUACION_EXTREMADURA_ESO;
      default: return CRITERIOS_EVALUACION_EXTREMADURA_PRIMARIA;
    }
  }
  if (comunidad === 'Región de Murcia') {
    switch (etapa) {
      case 'Primaria': return CRITERIOS_EVALUACION_MURCIA_PRIMARIA;
      case 'ESO': return CRITERIOS_EVALUACION_MURCIA_ESO;
      default: return CRITERIOS_EVALUACION_MURCIA_PRIMARIA;
    }
  }
  if (comunidad === 'Aragón') {
    switch (etapa) {
      case 'Primaria': return CRITERIOS_EVALUACION_ARAGON_PRIMARIA;
      case 'ESO': return CRITERIOS_EVALUACION_ARAGON_ESO;
      default: return CRITERIOS_EVALUACION_ARAGON_PRIMARIA;
    }
  }
  if (comunidad === 'Asturias') {
    switch (etapa) {
      case 'Primaria': return CRITERIOS_EVALUACION_ASTURIAS_PRIMARIA;
      case 'ESO': return CRITERIOS_EVALUACION_ASTURIAS_ESO;
      default: return CRITERIOS_EVALUACION_ASTURIAS_PRIMARIA;
    }
  }
  if (comunidad === 'Cantabria') {
    switch (etapa) {
      case 'Primaria': return CRITERIOS_EVALUACION_CANTABRIA_PRIMARIA;
      case 'ESO': return CRITERIOS_EVALUACION_CANTABRIA_ESO;
      default: return CRITERIOS_EVALUACION_CANTABRIA_PRIMARIA;
    }
  }
  if (comunidad === 'Galicia') {
    switch (etapa) {
      case 'Primaria': return CRITERIOS_EVALUACION_GALICIA_PRIMARIA;
      case 'ESO': return CRITERIOS_EVALUACION_GALICIA_ESO;
      default: return CRITERIOS_EVALUACION_GALICIA_PRIMARIA;
    }
  }
  if (comunidad === 'Catalunya' || comunidad === 'Catalunya') {
    switch (etapa) {
      case 'Primaria': return CRITERIOS_EVALUACION_CATALUNYA_PRIMARIA;
      case 'ESO': return CRITERIOS_EVALUACION_CATALUNYA_ESO;
      default: return CRITERIOS_EVALUACION_CATALUNYA_PRIMARIA;
    }
  }
  if (comunidad === 'Comunidad Valenciana') {
    switch (etapa) {
      case 'Primaria': return CRITERIOS_EVALUACION_VALENCIA_PRIMARIA;
      case 'ESO': return CRITERIOS_EVALUACION_VALENCIA_ESO;
      default: return CRITERIOS_EVALUACION_VALENCIA_PRIMARIA;
    }
  }
  if (comunidad === 'La Rioja') {
    switch (etapa) {
      case 'Primaria': return CRITERIOS_EVALUACION_LA_RIOJA_PRIMARIA;
      case 'ESO': return CRITERIOS_EVALUACION_LA_RIOJA_ESO;
      default: return CRITERIOS_EVALUACION_LA_RIOJA_PRIMARIA;
    }
  }
  if (comunidad === 'Comunidad de Madrid') {
    switch (etapa) {
      case 'Primaria': return CRITERIOS_EVALUACION_MADRID_PRIMARIA;
      case 'ESO': return CRITERIOS_EVALUACION_MADRID_ESO;
      default: return CRITERIOS_EVALUACION_MADRID_PRIMARIA;
    }
  }
  if (comunidad === 'Navarra') {
    switch (etapa) {
      case 'Primaria': return CRITERIOS_EVALUACION_NAVARRA_PRIMARIA;
      case 'ESO': return CRITERIOS_EVALUACION_NAVARRA_ESO;
      default: return CRITERIOS_EVALUACION_NAVARRA_PRIMARIA;
    }
  }
  if (comunidad === 'País Vasco') {
    switch (etapa) {
      case 'Primaria': return CRITERIOS_EVALUACION_PAIS_VASCO_PRIMARIA;
      case 'ESO': return CRITERIOS_EVALUACION_PAIS_VASCO_ESO;
      default: return CRITERIOS_EVALUACION_PAIS_VASCO_PRIMARIA;
    }
  }

  if (comunidad === 'Andalucía') {
    switch (etapa) {
      case 'Infantil': return CRITERIOS_EVALUACION_INFANTIL;
      case 'Primaria': return CRITERIOS_EVALUACION_ANDALUCIA_PRIMARIA;
      case 'ESO': return CRITERIOS_EVALUACION_ANDALUCIA_ESO;
      case 'Bachillerato': return CRITERIOS_EVALUACION_BACHILLERATO;
      default: return CRITERIOS_EVALUACION_ANDALUCIA_PRIMARIA;
    }
  }

  // Fallback
  switch (etapa) {
    case 'Infantil': return CRITERIOS_EVALUACION_INFANTIL;
    case 'Primaria': return CRITERIOS_EVALUACION_EF;
    case 'ESO': return CRITERIOS_EVALUACION_ESO;
    case 'Bachillerato': return CRITERIOS_EVALUACION_BACHILLERATO;
    default: return CRITERIOS_EVALUACION_EF;
  }
}

export function getSaberesByEtapa(etapa: EtapaEducativa, comunidad: ComunidadAutonoma = 'Andalucía'): SaberBasico[] {
  if (comunidad === 'Castilla y León') {
    switch (etapa) {
      case 'Primaria': return SABERES_BASICOS_CYL_PRIMARIA;
      case 'ESO': return SABERES_BASICOS_CYL_ESO;
      default: return SABERES_BASICOS_CYL_PRIMARIA;
    }
  }
  if (comunidad === 'Castilla-La Mancha') {
    switch (etapa) {
      case 'Primaria': return SABERES_BASICOS_CLM_PRIMARIA;
      case 'ESO': return SABERES_BASICOS_CLM_ESO;
      default: return SABERES_BASICOS_CLM_PRIMARIA;
    }
  }
  if (comunidad === 'Extremadura') {
    switch (etapa) {
      case 'Primaria': return SABERES_BASICOS_EXTREMADURA_PRIMARIA;
      case 'ESO': return SABERES_BASICOS_EXTREMADURA_ESO;
      default: return SABERES_BASICOS_EXTREMADURA_PRIMARIA;
    }
  }
  if (comunidad === 'Región de Murcia') {
    switch (etapa) {
      case 'Primaria': return SABERES_BASICOS_MURCIA_PRIMARIA;
      case 'ESO': return SABERES_BASICOS_MURCIA_ESO;
      default: return SABERES_BASICOS_MURCIA_PRIMARIA;
    }
  }
  if (comunidad === 'Aragón') {
    switch (etapa) {
      case 'Primaria': return SABERES_BASICOS_ARAGON_PRIMARIA;
      case 'ESO': return SABERES_BASICOS_ARAGON_ESO;
      default: return SABERES_BASICOS_ARAGON_PRIMARIA;
    }
  }
  if (comunidad === 'Asturias') {
    switch (etapa) {
      case 'Primaria': return SABERES_BASICOS_ASTURIAS_PRIMARIA;
      case 'ESO': return SABERES_BASICOS_ASTURIAS_ESO;
      default: return SABERES_BASICOS_ASTURIAS_PRIMARIA;
    }
  }
  if (comunidad === 'Cantabria') {
    switch (etapa) {
      case 'Primaria': return SABERES_BASICOS_CANTABRIA_PRIMARIA;
      case 'ESO': return SABERES_BASICOS_CANTABRIA_ESO;
      default: return SABERES_BASICOS_CANTABRIA_PRIMARIA;
    }
  }
  if (comunidad === 'Galicia') {
    switch (etapa) {
      case 'Primaria': return SABERES_BASICOS_GALICIA_PRIMARIA;
      case 'ESO': return SABERES_BASICOS_GALICIA_ESO;
      default: return SABERES_BASICOS_GALICIA_PRIMARIA;
    }
  }
  if (comunidad === 'Catalunya' || comunidad === 'Catalunya') {
    switch (etapa) {
      case 'Primaria': return SABERES_BASICOS_CATALUNYA_PRIMARIA;
      case 'ESO': return SABERES_BASICOS_CATALUNYA_ESO;
      default: return SABERES_BASICOS_CATALUNYA_PRIMARIA;
    }
  }
  if (comunidad === 'Comunidad Valenciana') {
    switch (etapa) {
      case 'Primaria': return SABERES_BASICOS_VALENCIA_PRIMARIA;
      case 'ESO': return SABERES_BASICOS_VALENCIA_ESO;
      default: return SABERES_BASICOS_VALENCIA_PRIMARIA;
    }
  }
  if (comunidad === 'La Rioja') {
    switch (etapa) {
      case 'Primaria': return SABERES_BASICOS_LA_RIOJA_PRIMARIA;
      case 'ESO': return SABERES_BASICOS_LA_RIOJA_ESO;
      default: return SABERES_BASICOS_LA_RIOJA_PRIMARIA;
    }
  }
  if (comunidad === 'Comunidad de Madrid') {
    switch (etapa) {
      case 'Primaria': return SABERES_BASICOS_MADRID_PRIMARIA;
      case 'ESO': return SABERES_BASICOS_MADRID_ESO;
      default: return SABERES_BASICOS_MADRID_PRIMARIA;
    }
  }
  if (comunidad === 'Navarra') {
    switch (etapa) {
      case 'Primaria': return SABERES_BASICOS_NAVARRA_PRIMARIA;
      case 'ESO': return SABERES_BASICOS_NAVARRA_ESO;
      default: return SABERES_BASICOS_NAVARRA_PRIMARIA;
    }
  }
  if (comunidad === 'País Vasco') {
    switch (etapa) {
      case 'Primaria': return SABERES_BASICOS_PAIS_VASCO_PRIMARIA;
      case 'ESO': return SABERES_BASICOS_PAIS_VASCO_ESO;
      default: return SABERES_BASICOS_PAIS_VASCO_PRIMARIA;
    }
  }

  if (comunidad === 'Andalucía') {
    switch (etapa) {
      case 'Infantil': return SABERES_BASICOS_INFANTIL;
      case 'Primaria': return SABERES_BASICOS_ANDALUCIA_PRIMARIA;
      case 'ESO': return SABERES_BASICOS_ANDALUCIA_ESO;
      case 'Bachillerato': return SABERES_BASICOS_BACHILLERATO;
      default: return SABERES_BASICOS_ANDALUCIA_PRIMARIA;
    }
  }

  // Fallback
  switch (etapa) {
    case 'Infantil': return SABERES_BASICOS_INFANTIL;
    case 'Primaria': return SABERES_BASICOS_EF;
    case 'ESO': return SABERES_BASICOS_ESO;
    case 'Bachillerato': return SABERES_BASICOS_BACHILLERATO;
    default: return SABERES_BASICOS_EF;
  }
}

// Para utilidades genéricas donde no sabemos la etapa y buscamos por ID,
// unificamos todas en tiempo de ejecución.
export const TODAS_LAS_COMPETENCIAS = [
  ...COMPETENCIAS_ESPECIFICAS_EF,
  ...COMPETENCIAS_ESPECIFICAS_INFANTIL,
  ...COMPETENCIAS_ESPECIFICAS_ESO,
  ...COMPETENCIAS_ESPECIFICAS_BACHILLERATO,
  ...COMPETENCIAS_ESPECIFICAS_ANDALUCIA_PRIMARIA,
  ...COMPETENCIAS_ESPECIFICAS_ANDALUCIA_ESO,
  ...COMPETENCIAS_ESPECIFICAS_CYL_PRIMARIA,
  ...COMPETENCIAS_ESPECIFICAS_CYL_ESO,
  ...COMPETENCIAS_ESPECIFICAS_CLM_PRIMARIA,
  ...COMPETENCIAS_ESPECIFICAS_CLM_ESO,
  ...COMPETENCIAS_ESPECIFICAS_EXTREMADURA_PRIMARIA,
  ...COMPETENCIAS_ESPECIFICAS_EXTREMADURA_ESO,
  ...COMPETENCIAS_ESPECIFICAS_MURCIA_PRIMARIA,
  ...COMPETENCIAS_ESPECIFICAS_MURCIA_ESO,
  ...COMPETENCIAS_ESPECIFICAS_ARAGON_PRIMARIA,
  ...COMPETENCIAS_ESPECIFICAS_ARAGON_ESO,
  ...COMPETENCIAS_ESPECIFICAS_ASTURIAS_PRIMARIA,
  ...COMPETENCIAS_ESPECIFICAS_ASTURIAS_ESO,
  ...COMPETENCIAS_ESPECIFICAS_CANTABRIA_PRIMARIA,
  ...COMPETENCIAS_ESPECIFICAS_CANTABRIA_ESO,
  ...COMPETENCIAS_ESPECIFICAS_GALICIA_PRIMARIA,
  ...COMPETENCIAS_ESPECIFICAS_GALICIA_ESO,
  ...COMPETENCIAS_ESPECIFICAS_CATALUNYA_PRIMARIA,
  ...COMPETENCIAS_ESPECIFICAS_CATALUNYA_ESO,
  ...COMPETENCIAS_ESPECIFICAS_VALENCIA_PRIMARIA,
  ...COMPETENCIAS_ESPECIFICAS_VALENCIA_ESO,
  ...COMPETENCIAS_ESPECIFICAS_LA_RIOJA_PRIMARIA,
  ...COMPETENCIAS_ESPECIFICAS_LA_RIOJA_ESO,
  ...COMPETENCIAS_ESPECIFICAS_MADRID_PRIMARIA,
  ...COMPETENCIAS_ESPECIFICAS_MADRID_ESO,
  ...COMPETENCIAS_ESPECIFICAS_NAVARRA_PRIMARIA,
  ...COMPETENCIAS_ESPECIFICAS_NAVARRA_ESO,
  ...COMPETENCIAS_ESPECIFICAS_PAIS_VASCO_PRIMARIA,
  ...COMPETENCIAS_ESPECIFICAS_PAIS_VASCO_ESO
];

export const TODOS_LOS_CRITERIOS = [
  ...CRITERIOS_EVALUACION_EF,
  ...CRITERIOS_EVALUACION_INFANTIL,
  ...CRITERIOS_EVALUACION_ESO,
  ...CRITERIOS_EVALUACION_BACHILLERATO,
  ...CRITERIOS_EVALUACION_ANDALUCIA_PRIMARIA,
  ...CRITERIOS_EVALUACION_ANDALUCIA_ESO,
  ...CRITERIOS_EVALUACION_CYL_PRIMARIA,
  ...CRITERIOS_EVALUACION_CYL_ESO,
  ...CRITERIOS_EVALUACION_CLM_PRIMARIA,
  ...CRITERIOS_EVALUACION_CLM_ESO,
  ...CRITERIOS_EVALUACION_EXTREMADURA_PRIMARIA,
  ...CRITERIOS_EVALUACION_EXTREMADURA_ESO,
  ...CRITERIOS_EVALUACION_MURCIA_PRIMARIA,
  ...CRITERIOS_EVALUACION_MURCIA_ESO,
  ...CRITERIOS_EVALUACION_ARAGON_PRIMARIA,
  ...CRITERIOS_EVALUACION_ARAGON_ESO,
  ...CRITERIOS_EVALUACION_ASTURIAS_PRIMARIA,
  ...CRITERIOS_EVALUACION_ASTURIAS_ESO,
  ...CRITERIOS_EVALUACION_CANTABRIA_PRIMARIA,
  ...CRITERIOS_EVALUACION_CANTABRIA_ESO,
  ...CRITERIOS_EVALUACION_GALICIA_PRIMARIA,
  ...CRITERIOS_EVALUACION_GALICIA_ESO,
  ...CRITERIOS_EVALUACION_CATALUNYA_PRIMARIA,
  ...CRITERIOS_EVALUACION_CATALUNYA_ESO,
  ...CRITERIOS_EVALUACION_VALENCIA_PRIMARIA,
  ...CRITERIOS_EVALUACION_VALENCIA_ESO,
  ...CRITERIOS_EVALUACION_LA_RIOJA_PRIMARIA,
  ...CRITERIOS_EVALUACION_LA_RIOJA_ESO,
  ...CRITERIOS_EVALUACION_MADRID_PRIMARIA,
  ...CRITERIOS_EVALUACION_MADRID_ESO,
  ...CRITERIOS_EVALUACION_NAVARRA_PRIMARIA,
  ...CRITERIOS_EVALUACION_NAVARRA_ESO,
  ...CRITERIOS_EVALUACION_PAIS_VASCO_PRIMARIA,
  ...CRITERIOS_EVALUACION_PAIS_VASCO_ESO
];

export const TODOS_LOS_SABERES = [
  ...SABERES_BASICOS_EF,
  ...SABERES_BASICOS_INFANTIL,
  ...SABERES_BASICOS_ESO,
  ...SABERES_BASICOS_BACHILLERATO,
  ...SABERES_BASICOS_ANDALUCIA_PRIMARIA,
  ...SABERES_BASICOS_ANDALUCIA_ESO,
  ...SABERES_BASICOS_CYL_PRIMARIA,
  ...SABERES_BASICOS_CYL_ESO,
  ...SABERES_BASICOS_CLM_PRIMARIA,
  ...SABERES_BASICOS_CLM_ESO,
  ...SABERES_BASICOS_EXTREMADURA_PRIMARIA,
  ...SABERES_BASICOS_EXTREMADURA_ESO,
  ...SABERES_BASICOS_MURCIA_PRIMARIA,
  ...SABERES_BASICOS_MURCIA_ESO,
  ...SABERES_BASICOS_ARAGON_PRIMARIA,
  ...SABERES_BASICOS_ARAGON_ESO,
  ...SABERES_BASICOS_ASTURIAS_PRIMARIA,
  ...SABERES_BASICOS_ASTURIAS_ESO,
  ...SABERES_BASICOS_CANTABRIA_PRIMARIA,
  ...SABERES_BASICOS_CANTABRIA_ESO,
  ...SABERES_BASICOS_GALICIA_PRIMARIA,
  ...SABERES_BASICOS_GALICIA_ESO,
  ...SABERES_BASICOS_CATALUNYA_PRIMARIA,
  ...SABERES_BASICOS_CATALUNYA_ESO,
  ...SABERES_BASICOS_VALENCIA_PRIMARIA,
  ...SABERES_BASICOS_VALENCIA_ESO,
  ...SABERES_BASICOS_LA_RIOJA_PRIMARIA,
  ...SABERES_BASICOS_LA_RIOJA_ESO,
  ...SABERES_BASICOS_MADRID_PRIMARIA,
  ...SABERES_BASICOS_MADRID_ESO,
  ...SABERES_BASICOS_NAVARRA_PRIMARIA,
  ...SABERES_BASICOS_NAVARRA_ESO,
  ...SABERES_BASICOS_PAIS_VASCO_PRIMARIA,
  ...SABERES_BASICOS_PAIS_VASCO_ESO
];
